"""rename metadata column to message_metadata

Revision ID: 9fa90d9f40af
Revises: 79b78c01732e
Create Date: 2024-10-29 18:09:50.545863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fa90d9f40af'
down_revision = '79b78c01732e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message_metadata', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('message_metadata')

    # ### end Alembic commands ###
